### ISSUE TITLE
想请教下run_classification中my_config各项参数的设置

### ISSUE THREAD

**Issue by KarryBanana** [zkcpku/HGT-HPG#2]
您好！我在尝试运行`codenet_py_classification`目录下的`run_classification.py`文件，其中涉及到许多`my_config`参数的设置。我尝试根据您论文中实验部分的参数自行创建了一个`my_config`，如下图：
![image](https://user-images.githubusercontent.com/25265710/220634977-9fa97fbe-e767-45fb-abec-b046be87ec24.png)
![image](https://user-images.githubusercontent.com/25265710/220634976-3553d2bc-3507-4ba6-a976-45e6d3784b75.png)

不过我在一张RTX3090上运行后发现训练时间似乎特别久，一个`epoch`训练时间达到了几小时。

![dad196f4fc97bb579d49e247db2a737](https://user-images.githubusercontent.com/25265710/220637158-b3067d72-bbd0-4977-a2bd-0fef3504d094.png)

因此想向作者您请教上图中的参数设置是否有误（或者您是否能提供`my_config`中训练有关参数的具体数据），另外也想向您请教下V100在`codenet`数据集上训练分类任务的时间大概是多长。

期待您的回复与指点，谢谢！

**Comment by TangFanggeng** [comment]
> 您好！我在尝试运行`codenet_py_classification`目录下的`run_classification.py`文件，其中涉及到许多`my_config`参数的设置。我尝试根据您论文中实验部分的参数自行创建了一个`my_config`，如下图： ![image](https://user-images.githubusercontent.com/25265710/220634977-9fa97fbe-e767-45fb-abec-b046be87ec24.png) ![image](https://user-images.githubusercontent.com/25265710/220634976-3553d2bc-3507-4ba6-a976-45e6d3784b75.png)
> 
> 不过我在一张RTX3090上运行后发现训练时间似乎特别久，一个`epoch`训练时间达到了几小时。
> 
> ![dad196f4fc97bb579d49e247db2a737](https://user-images.githubusercontent.com/25265710/220637158-b3067d72-bbd0-4977-a2bd-0fef3504d094.png)
> 
> 因此想向作者您请教上图中的参数设置是否有误（或者您是否能提供`my_config`中训练有关参数的具体数据），另外也想向您请教下V100在`codenet`数据集上训练分类任务的时间大概是多长。
> 
> 期待您的回复与指点，谢谢！

请问java_parser文件夹下面的那个java_asdl.pkl应该如何得到啊

**Comment by zkcpku** [comment]
Sorry for my late response.
1. 对于模型训练，这个工作开始的时期较早，使用的是naive版本的HGT的实现，训练效率确实受很大影响。我们当时的训练控制在15个epoch以内取validation集上的最好checkpoint。我注意到新版的DGL官方已经实现了HGT模型，并对速度进行了优化，建议您可以尝试一下。我也会在空闲时间尝试维护更新一下这个repo的实现。
2. 对于java_asdl.pkl，我检查后发现因为gitignore的原因遗失了部分后缀名的文件。我会在个人服务器上检查一下。
